### ISSUE TITLE
These utils are awesome (only a paginator for now)

### ISSUE THREAD

**Issue by ArjixWasTaken** [zeqxc/WrongUtils#1]
I just wanted to give my thanks to you, you saved me hours of headache on how to make a pagination system.

**Comment by wrongyn** [comment]
> I just wanted to give my thanks to you, you saved me hours of headache on how to make a pagination system.

Haha no problem good luck with the paginator. Planning to add more utils when I’m motivated in the future.

**Comment by ArjixWasTaken** [comment]
The paginator works fine for me so I don't need that luck, keep it you will need it to add more awesome features 😄
